/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-04-08 19:04:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class lead_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Thêm mới Lead</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: #f0f2f5; font-family: 'Inter', sans-serif; }\r\n");
      out.write("        .form-card { border: none; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.08); background: #fff; }\r\n");
      out.write("        .form-label { font-weight: 600; color: #495057; font-size: 0.9rem; }\r\n");
      out.write("        .input-group-text { border: none; background-color: #f8f9fa; color: #adb5bd; }\r\n");
      out.write("        .form-control, .form-select { border: 1px solid #e9ecef; padding: 0.6rem 1rem; }\r\n");
      out.write("        .form-control:focus { border-color: #0d6efd; box-shadow: none; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-9\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <a href=\"leads\" class=\"btn btn-link text-decoration-none p-0 text-secondary\">\r\n");
      out.write("                    <i class=\"fa-solid fa-chevron-left me-1\"></i> Trở lại danh sách\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card form-card p-4 p-md-5\">\r\n");
      out.write("                <div class=\"text-center mb-5\">\r\n");
      out.write("                    <h2 class=\"fw-bold\">Thông tin Khách hàng Mới</h2>\r\n");
      out.write("                    <p class=\"text-muted\">Vui lòng điền đầy đủ các thông tin để tạo Lead trong hệ thống</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"leads?action=insert\" method=\"post\">\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 class=\"text-primary mb-4 fw-bold border-bottom pb-2\">1. Thông tin định danh</h5>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Tên công ty / Website</label>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-text\"><i class=\"fa-solid fa-building\"></i></span>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"company_name\" placeholder=\"Tên công ty hoặc URL website\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Tên người liên hệ (*)</label>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-text\"><i class=\"fa-solid fa-user\"></i></span>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"contact_name\" placeholder=\"Nhập họ và tên khách\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Số CCCD / CMND</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"citizen_id\" placeholder=\"Citizen ID\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Mã số thuế</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"tax_code\" placeholder=\"Tax Code\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h5 class=\"text-primary mb-4 mt-4 fw-bold border-bottom pb-2\">2. Liên hệ & Kinh doanh</h5>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Số điện thoại</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"phone\" placeholder=\"VD: 0912...\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Email cá nhân/công ty</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"example@gmail.com\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Loại khách hàng</label>\r\n");
      out.write("                            <select class=\"form-select\" name=\"customer_type\">\r\n");
      out.write("                                <option value=\"B2B\">Doanh nghiệp (B2B)</option>\r\n");
      out.write("                                <option value=\"B2C\">Cá nhân (B2C)</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Doanh thu dự kiến</label>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-text\">$</span>\r\n");
      out.write("                                <input type=\"number\" step=\"0.01\" class=\"form-control\" name=\"expected_revenue\" placeholder=\"0.00\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Trạng thái</label>\r\n");
      out.write("                            <select class=\"form-select\" name=\"status\">\r\n");
      out.write("                                <option value=\"Mới\">Mới</option>\r\n");
      out.write("                                <option value=\"Đang tiếp cận\">Đang tiếp cận</option>\r\n");
      out.write("                                <option value=\"Tiềm năng\">Tiềm năng</option>\r\n");
      out.write("                                <option value=\"Thất bại\">Thất bại</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Địa chỉ</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"address\" placeholder=\"Số nhà, đường, phường, quận...\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 mb-4\">\r\n");
      out.write("                            <label class=\"form-label\">Mô tả chi tiết / Ghi chú</label>\r\n");
      out.write("                            <textarea class=\"form-control\" name=\"description\" rows=\"3\" placeholder=\"Nhập các đặc điểm lưu ý về khách hàng...\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"d-grid gap-2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary btn-lg fw-bold py-3 shadow\">\r\n");
      out.write("                            <i class=\"fa-solid fa-cloud-arrow-up me-2\"></i>Lưu thông tin khách hàng\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
